name: Build Docker and Push Image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mi-app-flask:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mi-app-flask:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install Docker in AWS instance
        uses: aws-actions/amazon-ssm-run-command@v3
        with:
          instance-ids: 'i-0a59861bcbc05c3ef'
          comment: 'Install Docker on EC2 instance'
          parameters: |
            commands:
              - |
                sudo apt update -y
                sudo apt upgrade -y
                sudo apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
                sudo usermode -aG docker ubuntu
                sudo systemctl restart docker