name: Worflow Testing Github Actions

on:
  push:
    branches:
      - main

jobs:
  simple_test:
    runs-on: ubuntu-latest

    steps:
      - name: Simple echo step
        run: |
          echo 'Hello from github actions'
          echo 'Basic workflow from github actions'