name: CI Docker Build and Deploy (CLI SSM FINAL - Base64 Script)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mi-app-flask:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Get Lowercase Docker Hub Username
        id: get_lower_username
        run: |
          LOWER_USERNAME=$(echo "${{ secrets.DOCKERHUB_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=lower_username::$LOWER_USERNAME"
      
      - name: Create Deploy Script Content (Base64)
        id: script_content
        run: |
          # Obtener el nombre de usuario en minúsculas de la salida del paso anterior
          LOWER_USERNAME="${{ steps.get_lower_username.outputs.lower_username }}"

          # Definir el contenido completo del script deploy.sh como un string multilinea
          # Usamos read -r -d '' <<EOF para leer el contenido hasta EOF
          # Las variables de shell ($CONTAINER_NAME, $IMAGE_NAME) se dejan tal cual las queremos en el script final
          # Las comillas y backslashes dentro del script final se dejan tal cual las queremos
          read -r -d '' SCRIPT_CONTENT <<'EOF_SCRIPT' || true
          #!/bin/bash

          CONTAINER_NAME="my-flask-app-container"
          IMAGE_NAME="$LOWER_USERNAME/mi-app-flask:latest" # Usamos la variable con el nombre en minúsculas

          echo "Deteniendo y eliminando contenedor existente (\$CONTAINER_NAME)..."
          docker stop \$CONTAINER_NAME > /dev/null 2>&1 || true
          docker rm \$CONTAINER_NAME > /dev/null 2>&1 || true
          echo "Contenedor existente detenido/eliminado."

          echo "Jalando la última imagen de Docker Hub (\$IMAGE_NAME)..."
          docker pull \$IMAGE_NAME
          echo "Imagen jalada."

          echo "Ejecutando nuevo contenedor (\$CONTAINER_NAME)..."
          docker run -d --name \$CONTAINER_NAME -p 80:5000 \$IMAGE_NAME
          echo "Nuevo contenedor en ejecución."

          echo "Despliegue completado."
          EOF_SCRIPT
          
          # Codificar el contenido del script a Base64
          BASE64_SCRIPT=$(echo "$SCRIPT_CONTENT" | base64 -w 0)
          
          # Guardar la cadena Base64 como una salida del paso
          echo "::set-output name=base64_script::$BASE64_SCRIPT"

      - name: Execute Script via SSM (Base64)
        run: |
          # Obtener la cadena Base64 del contenido del script del paso anterior
          BASE64_SCRIPT_CONTENT="${{ steps.script_content.outputs.base64_script }}"

          # Enviar el comando via SSM: hacer echo de la cadena Base64, decodificarla y pasarla a bash para ejecución
          aws ssm send-command \
            --instance-ids '["i-0bc4ea18eca61778df"]' \ # Tu ID de instancia
            --document-name "AWS-RunShellScript" \
            --comment "Execute script (Base64 encoded)" \
            --parameters commands='["echo \"'$BASE64_SCRIPT_CONTENT'\" | base64 -d | bash"]' \ # Comando simple: echo base64 | base64 -d | bash
            --region us-east-2 # Tu región

      - name: Final Verification Step (Optional)
        run: echo "Script execution command sent via SSM Base64."