name: Build Docker and Push Image to DockerHub

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push to DockerHub
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mi-app-flask:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mi-app-flask:latest